### ISSUE TITLE
Incomplete translation

### ISSUE THREAD

**Issue by tripleo1** [undefinedDarkness/ewwxml#2]
See: https://gist.github.com/tripleo1/d9acc571c27ad2fa5da77b4e698ee4b5

1. Missing closing paren at defwidget user
2. Missing closing paren at defwidget apps
3. Unconverted xml at defwidget folders/genwin/hddbox

From: https://github.com/adi1090x/widgets
https://github.com/adi1090x/widgets/nordic/eww.xml

**Comment by davidnoronha1** [comment]
Does the latest commit (9fbfe5a) fix it for you?

**Comment by tripleo1** [comment]
Yes much better.
